spring:
  application:
    name: jacory-space-api

  datasource:
    url: jdbc:mysql://localhost:3306/jacory_system?useSSL=false&serverTimezone=UTC
    username: root
    password: Jinchengyue1124@
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 2037